spring.application.name=user

server.port=8081

spring.datasource.url= jdbc:postgresql://localhost:5432/ms-user
spring.datasource.username=login
spring.datasource.password=senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.rabbitmq.addresses=link-do-rabbitmq

broker.queue.email.name=default.email

