spring.application.name=email

server.port=8082

spring.datasource.url= jdbc:postgresql://localhost:5432/ms-email
spring.datasource.username=login
spring.datasource.password=senha
spring.jpa.hibernate.ddl-auto=update



spring.rabbitmq.addresses=link-do-rabbitmq

broker.queue.email.name=nome-da-queue

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email-usado-para-enviar
spring.mail.password=senha-de-app-google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
